name: go
on:
  pull_request:
  push:
    branches:
      - main
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v5
        with:
          go-version: '1.21'
      - name: lint
        uses: golangci/golangci-lint-action@v4
        with:
          version: v1.56.1
      - name: run tests
        run: go test ./...
